---
version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.10
    steps:
      - checkout
      - run: go build -o openstack -ldflags="-s -w"
      - store_artifacts:
          path: openstack
...