---
version: 2
jobs:
  build:
    docker:
      - image: pbacterio/circleci-golang-upx
    steps:
      - checkout
      - run: go build -o openstack -ldflags="-s -w"
      - run: upx --best --ultra-brute openstack
      - store_artifacts:
          path: openstack
...